### ISSUE TITLE
New version broke mapboxnavigation-ios-binding

### ISSUE THREAD

**Issue by JFDionne** [NAXAM/mapbox-ios-binding#9]
Hi @fleuverouge , thank for this update, but I think this new version broke mapboxnavigation-ios-binding.

dyld: Symbol not found: _OBJC_CLASS_$_MGLCameraStyleFunction

** I like your name :)

**Comment by fleuverouge** [comment]
Hi @JFDionne Thanks for reaching to us.
Since version 4.0.x, Mapbox replaced MGLStyleValue and its subclasses by NSExpression.

The Mapbox Navigation iOS binding is a separated project and it depends on several libraries which take much more time to update while it is not in our high-priority plans. So it'd be great if you or anybody help to contribute to that repository :)

**Comment by JFDionne** [comment]
@fleuverouge Sure, but I don't how you do it, I check on the Android version, but I'm lost.
Do you have any "howto" ?

**Comment by fleuverouge** [comment]
Hi @JFDionne You may find tutorials for binding iOS libraries in [Xamarin official documentation](https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/) and [this blog post](https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76).
